export const data = [{
    "Id": 1,
  "Date": "6/8/2024",
  "TournamentName": "Jarrold",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/28/2024",
  "League": "Lydon"
}, {
  "Id": 2,
  "Date": "6/12/2024",
  "TournamentName": "MacGruer",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/29/2024",
  "League": "Allen"
}, {
  "Id": 3,
  "Date": "5/25/2024",
  "TournamentName": "Ratcliffe",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/17/2024",
  "League": "Duke"
}, {
  "Id": 4,
  "Date": "6/13/2024",
  "TournamentName": "Reely",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/30/2024",
  "League": "Francois"
}, {
  "Id": 5,
  "Date": "5/9/2024",
  "TournamentName": "Bonar",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/26/2024",
  "League": "Haleigh"
}, {
  "Id": 6,
  "Date": "6/19/2024",
  "TournamentName": "Fernyhough",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/25/2024",
  "League": "Paco"
}, {
  "Id": 7,
  "Date": "5/10/2024",
  "TournamentName": "Screech",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/27/2024",
  "League": "Dunstan"
}, {
  "Id": 8,
  "Date": "5/14/2024",
  "TournamentName": "Hamblen",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/18/2024",
  "League": "Wakefield"
}, {
  "Id": 9,
  "Date": "5/22/2024",
  "TournamentName": "Oxtiby",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/17/2024",
  "League": "Bernhard"
}, {
  "Id": 10,
  "Date": "5/20/2024",
  "TournamentName": "Rosel",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/18/2024",
  "League": "Neall"
}, {
  "Id": 11,
  "Date": "6/8/2024",
  "TournamentName": "Winser",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/27/2024",
  "League": "Thornton"
}, {
  "Id": 12,
  "Date": "6/6/2024",
  "TournamentName": "Cammell",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/29/2024",
  "League": "Cullie"
}, {
  "Id": 13,
  "Date": "6/8/2024",
  "TournamentName": "Keerl",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/23/2024",
  "League": "Chet"
}, {
  "Id": 14,
  "Date": "6/19/2024",
  "TournamentName": "Denk",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/21/2024",
  "League": "Si"
}, {
  "Id": 15,
  "Date": "6/6/2024",
  "TournamentName": "Woodfield",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/26/2024",
  "League": "Dennis"
}, {
  "Id": 16,
  "Date": "6/3/2024",
  "TournamentName": "Crimmins",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/24/2024",
  "League": "Oberon"
}, {
  "Id": 17,
  "Date": "6/27/2024",
  "TournamentName": "Hedon",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/18/2024",
  "League": "Cecil"
}, {
  "Id": 18,
  "Date": "6/25/2024",
  "TournamentName": "Kilbee",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/22/2024",
  "League": "Godfrey"
}, {
  "Id": 19,
  "Date": "6/15/2024",
  "TournamentName": "Ellerker",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/30/2024",
  "League": "Vince"
}, {
  "Id": 20,
  "Date": "5/30/2024",
  "TournamentName": "Prandy",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/20/2024",
  "League": "Callean"
}, {
  "Id": 21,
  "Date": "5/16/2024",
  "TournamentName": "Earthfield",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/23/2024",
  "League": "Zeb"
}, {
  "Id": 22,
  "Date": "6/3/2024",
  "TournamentName": "Jamieson",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/22/2024",
  "League": "Ellary"
}, {
  "Id": 23,
  "Date": "5/28/2024",
  "TournamentName": "Frankel",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/16/2024",
  "League": "Kerr"
}, {
  "Id": 24,
  "Date": "6/2/2024",
  "TournamentName": "Studdert",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/16/2024",
  "League": "Cleve"
}, {
  "Id": 25,
  "Date": "5/17/2024",
  "TournamentName": "Howkins",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/30/2024",
  "League": "Isaiah"
}, {
  "Id": 26,
  "Date": "6/21/2024",
  "TournamentName": "Pee",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/17/2024",
  "League": "Raddie"
}, {
  "Id": 27,
  "Date": "6/4/2024",
  "TournamentName": "Fretter",
  "AgeGender": "Male",
  "RegistrationDeadline": "4/28/2024",
  "League": "Austen"
}, {
  "Id": 28,
  "Date": "6/1/2024",
  "TournamentName": "Fidoe",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/21/2024",
  "League": "Woodrow"
}, {
  "Id": 29,
  "Date": "6/30/2024",
  "TournamentName": "Perse",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/26/2024",
  "League": "Freddy"
}, {
  "Id": 30,
  "Date": "6/25/2024",
  "TournamentName": "Scay",
  "AgeGender": "Female",
  "RegistrationDeadline": "4/21/2024",
  "League": "Camey"
  }]